export const dishes_data = [
  {
    id: 1,
    imgUrl: "https://i.ibb.co/5nhD3W7/Image-6.png",
    name: "Spicy seasoned seafood noodles",
    cost: 2.29,
    number: 20,
    hot: true,
    cold: false,
    soup: true,
    grill: false,
    appetizer: false,
    dessert: false,
  },
  {
    id: 2,
    imgUrl: "https://i.ibb.co/dghm1vt/Image-5.png",
    name: "Salted Pasta with mushroom sauce",
    cost: 2.69,
    number: 20,
    hot: false,
    cold: false,
    soup: true,
    grill: false,
    appetizer: false,
    dessert: false,
  },
  {
    id: 3,
    imgUrl: "https://i.ibb.co/L8JkPBd/Image-3.png",
    name: "Hot spicy fried rice with omelet",
    cost: 3.29,
    number: 20,
    hot: true,
    cold: false,
    soup: false,
    grill: true,
    appetizer: false,
    dessert: false,
  },
  {
    id: 4,
    imgUrl: "https://i.ibb.co/qJrBnSp/Image-2.png",
    name: "Beef dumpling in hot and sour soup",
    cost: 4.29,
    number: 20,
    hot: false,
    cold: false,
    soup: false,
    grill: true,
    appetizer: false,
    dessert: false,
  },
  {
    id: 5,
    imgUrl: "https://i.ibb.co/syjRTkY/Image-1.png",
    name: "Spicy seasoned seafood noodles",
    cost: 2.89,
    number: 20,
    hot: false,
    cold: false,
    soup: false,
    grill: false,
    appetizer: false,
    dessert: true,
  },
  {
    id: 6,
    imgUrl: "https://i.ibb.co/5nhD3W7/Image-6.png",
    name: "Beef dumpling in hot and sour soup",
    cost: 2.39,
    number: 20,
    hot: true,
    cold: false,
    soup: true,
    grill: false,
    appetizer: false,
    dessert: false,
  },
  {
    id: 7,
    imgUrl: "https://i.ibb.co/L8JkPBd/Image-3.png",
    name: "Hot spicy fried rice with omelet",
    cost: 5.29,
    number: 20,
    hot: false,
    cold: false,
    soup: false,
    grill: false,
    appetizer: true,
    dessert: false,
  },
  {
    id: 8,
    imgUrl: "https://i.ibb.co/5nhD3W7/Image-6.png",
    name: "Spicy seasoned seafood noodles",
    cost: 2.29,
    number: 20,
    hot: true,
    cold: false,
    soup: false,
    grill: false,
    appetizer: false,
    dessert: true,
  },
  {
    id: 9,
    imgUrl: "https://i.ibb.co/dghm1vt/Image-5.png",
    name: "Salted Pasta with mushroom sauce",
    cost: 2.69,
    number: 20,
    hot: false,
    cold: false,
    soup: false,
    grill: true,
    appetizer: false,
    dessert: false,
  },
  {
    id: 10,
    imgUrl: "https://i.ibb.co/L8JkPBd/Image-3.png",
    name: "Hot spicy fried rice with omelet",
    cost: 3.29,
    number: 20,
    hot: true,
    cold: false,
    soup: true,
    grill: false,
    appetizer: false,
    dessert: false,
  },
  {
    id: 11,
    imgUrl: "https://i.ibb.co/qJrBnSp/Image-2.png",
    name: "Beef dumpling in hot and sour soup",
    cost: 4.29,
    number: 20,
    hot: false,
    cold: true,
    soup: false,
    grill: false,
    appetizer: false,
    dessert: false,
  },
  {
    id: 12,
    imgUrl: "https://i.ibb.co/syjRTkY/Image-1.png",
    name: "Spicy seasoned seafood noodles",
    cost: 2.89,
    number: 20,
    hot: false,
    cold: false,
    soup: true,
    grill: false,
    appetizer: false,
    dessert: false,
  },
  {
    id: 13,
    imgUrl: "https://i.ibb.co/5nhD3W7/Image-6.png",
    name: "Beef dumpling in hot and sour soup",
    cost: 2.39,
    number: 20,
    hot: false,
    cold: true,
    soup: false,
    grill: false,
    appetizer: false,
    dessert: false,
  },
  {
    id: 14,
    imgUrl: "https://i.ibb.co/L8JkPBd/Image-3.png",
    name: "Hot spicy fried rice with omelet",
    cost: 5.29,
    number: 20,
    hot: true,
    cold: false,
    soup: true,
    grill: false,
    appetizer: false,
    dessert: false,
  },
];
